services:
  - type: web
    name: iris-demo
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: ohio
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: IRIS_DB
        value: /tmp/iris.db
